# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"[\n\x11\x41\x64\x64ProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x14\n\x0cimage_base64\x18\x04 \x01(\t\"J\n\x12\x41\x64\x64ProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x32W\n\x0eProductService\x12\x45\n\nAddProduct\x12\x1a.product.AddProductRequest\x1a\x1b.product.AddProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDPRODUCTREQUEST']._serialized_start=26
  _globals['_ADDPRODUCTREQUEST']._serialized_end=117
  _globals['_ADDPRODUCTRESPONSE']._serialized_start=119
  _globals['_ADDPRODUCTRESPONSE']._serialized_end=193
  _globals['_PRODUCTSERVICE']._serialized_start=195
  _globals['_PRODUCTSERVICE']._serialized_end=282
# @@protoc_insertion_point(module_scope)
